# Generated by Django 4.2.7 on 2023-11-17 08:16

from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0017_django_price_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='meta',
            field=models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder),
        ),
    ]
