# Generated by Django 4.2.7 on 2023-11-17 08:16

from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_django_price_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='profile_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='meta',
            field=models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='private_meta',
            field=models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutline',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
