_("Regenerate workflow")
_("Workflow type")
_("Creation date")
_("Acceptance date")
_("Email")
_("Title")
_("Item description")
_("Status")
_("Download")
_("Accept")
_("Reject")
_("name")
_("description")
_("New")
_("Report type")
_("Date")
_("Update")
