_("Sign in")
_("Wrong login or password, try again")
_("User email")
_("User name")
_("User name or email")
_("Password")
_("or sign in with")
_("I forgot my password")
_("Register")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("Cancel")
_("OK")
_("Field")
_("Value")
_("Delete the item")
_("Refresh")
_("Import data to table")
_("Action")
_("get row")
_("new row")
_("Change password")
_("Manage")
_("Logout")
_("Login")
_("Search results")
_("Search")
_("Notifications")
_("Message")
_("You do not have permission to this option")
_("Back")
_("New element")
_("Whole Word")
_("Regular Expression")
