# Generated by Django 4.2.7 on 2023-11-17 08:16

import datetime
import django.core.serializers.json
from django.db import migrations, models
import django_fsm
import getpaid.types
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_django_price_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_locked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount locked with this payment, ready to charge.', max_digits=20, verbose_name='amount paid'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount actually paid.', max_digits=20, verbose_name='amount paid'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='amount refunded'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_required',
            field=models.DecimalField(decimal_places=2, default=False, help_text='Amount required to fulfill the payment; in selected currency, normal notation', max_digits=20, verbose_name='amount required'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='backend',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='backend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2023, 11, 17, 9, 16, 6, 129409), verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='external id'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fraud_message',
            field=models.TextField(blank=True, verbose_name='fraud message'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fraud_status',
            field=django_fsm.FSMField(choices=[('unknown', 'unknown'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('check', 'needs manual verification')], db_index=True, default=getpaid.types.FraudStatus['UNKNOWN'], max_length=20, protected=True, verbose_name='fraud status'),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_payment_on',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='paid on'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_on',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='refunded on'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'new'), ('prepared', 'in progress'), ('pre-auth', 'pre-authed'), ('charge_started', 'charge process started'), ('partially_paid', 'partially paid'), ('paid', 'paid'), ('failed', 'failed'), ('refund_started', 'refund started'), ('refunded', 'refunded')], db_index=True, default=getpaid.types.PaymentStatus['NEW'], max_length=50, protected=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway_response',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
