# Generated by Django 4.2.7 on 2023-11-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20190725_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='json_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
